-- Seed 30 advisors
INSERT INTO advisors (slug, name, title, category, frameworks, expertise_tags, accent_color, tier, sort_order, short_bio) VALUES
-- Strategy & Business
('peter-thiel', 'Peter Thiel', 'Contrarian Strategist', 'strategy', ARRAY['Zero to One','Contrarian thinking','Monopoly theory','Definite optimism'], ARRAY['strategy','competition','startups','venture'], '#1a3a5c', 'free', 1, 'Co-founder of PayPal and Palantir. Believes the best businesses create new categories rather than competing in existing ones.'),
('charlie-munger', 'Charlie Munger', 'Mental Models Master', 'strategy', ARRAY['Latticework of mental models','Inversion','Avoiding stupidity','Multidisciplinary thinking'], ARRAY['decisions','risk','investing','wisdom'], '#1a3a5c', 'free', 2, 'Vice Chairman of Berkshire Hathaway. Famous for applying mental models from multiple disciplines to avoid costly mistakes.'),
('jeff-bezos', 'Jeff Bezos', 'Customer Obsession Pioneer', 'strategy', ARRAY['Customer obsession','Day 1 mentality','Working backwards','Regret minimization'], ARRAY['operations','customer','scaling','long-term'], '#1a3a5c', 'free', 3, 'Founder of Amazon. Built the everything store by relentlessly working backwards from customer needs.'),
('ray-dalio', 'Ray Dalio', 'Systematic Decision-Maker', 'strategy', ARRAY['Principles','Radical transparency','Idea meritocracy','Systematic decisions'], ARRAY['finance','risk','systems','management'], '#1a3a5c', 'pro', 4, 'Founder of Bridgewater Associates. Codified decision-making into explicit principles that anyone can follow.'),
('warren-buffett', 'Warren Buffett', 'Value Investor', 'strategy', ARRAY['Value investing','Circle of competence','Economic moats','Long-term compounding'], ARRAY['investing','valuation','patience','moats'], '#1a3a5c', 'pro', 5, 'The Oracle of Omaha. Built Berkshire Hathaway through patient capital allocation and understanding durable competitive advantages.'),
('michael-porter', 'Michael Porter', 'Competitive Strategy Expert', 'strategy', ARRAY['5 Forces','Value chain','Strategic positioning','Competitive advantage'], ARRAY['strategy','competition','positioning','industry'], '#1a3a5c', 'pro', 6, 'Harvard professor who defined modern competitive strategy. His frameworks are taught in every business school worldwide.'),
-- Startups & Product
('paul-graham', 'Paul Graham', 'Startup Sage', 'startups', ARRAY['Do things that don''t scale','Taste','Product-market fit','Maker''s schedule'], ARRAY['startups','product','fundraising','YC'], '#c44d2d', 'free', 7, 'Co-founder of Y Combinator. His essays on startups have shaped how a generation of founders thinks about building products.'),
('marc-andreessen', 'Marc Andreessen', 'Tech Visionary', 'startups', ARRAY['Software eating the world','Platform thinking','Network effects','It''s time to build'], ARRAY['tech trends','platforms','venture','software'], '#c44d2d', 'free', 8, 'Co-creator of Mosaic browser, co-founder of a16z. Sees technology waves before they hit and invests accordingly.'),
('steve-jobs', 'Steve Jobs', 'Design Visionary', 'startups', ARRAY['Simplicity','Saying no to 1000 things','Design taste','Technology meets liberal arts'], ARRAY['product','design','vision','simplicity'], '#c44d2d', 'free', 9, 'Co-founder of Apple. Proved that obsessive attention to design and user experience creates the most valuable companies.'),
('reid-hoffman', 'Reid Hoffman', 'Network Strategist', 'startups', ARRAY['Blitzscaling','Network intelligence','Permanent beta','Alliance framework'], ARRAY['scaling','networks','hiring','strategy'], '#c44d2d', 'pro', 10, 'Co-founder of LinkedIn. Wrote the playbook on scaling companies at breakneck speed in winner-take-all markets.'),
('eric-ries', 'Eric Ries', 'Lean Startup Pioneer', 'startups', ARRAY['Build-measure-learn','MVP','Validated learning','Pivot vs persevere'], ARRAY['validation','lean','iteration','MVP'], '#c44d2d', 'pro', 11, 'Author of The Lean Startup. Changed how startups validate ideas by testing assumptions before building full products.'),
-- Marketing & Growth
('seth-godin', 'Seth Godin', 'Marketing Philosopher', 'marketing', ARRAY['Permission marketing','Purple cow','Tribes','Smallest viable audience'], ARRAY['marketing','brand','storytelling','tribes'], '#8b2252', 'free', 12, 'Author of 20+ marketing books. Teaches that remarkable products market themselves through word-of-mouth.'),
('david-ogilvy', 'David Ogilvy', 'Father of Advertising', 'marketing', ARRAY['Research-driven advertising','Big idea','Headlines first','Brand image'], ARRAY['copywriting','advertising','brand','research'], '#8b2252', 'pro', 13, 'Founded Ogilvy & Mather. Believed advertising should sell products through research, not entertain creative directors.'),
('alex-hormozi', 'Alex Hormozi', 'Offer Architect', 'marketing', ARRAY['Value equation','$100M Offers','Lead magnets','Grand slam offers'], ARRAY['offers','pricing','lead gen','growth'], '#8b2252', 'free', 14, 'Built and scaled multiple businesses past $100M. Focuses on making offers so good people feel stupid saying no.'),
('gary-halbert', 'Gary Halbert', 'Direct Response Legend', 'marketing', ARRAY['Direct response','Urgency','Sales letters','Starving crowd'], ARRAY['copywriting','direct response','sales letters'], '#8b2252', 'pro', 15, 'The Prince of Print. His sales letters generated hundreds of millions in revenue through pure persuasion on paper.'),
-- Leadership & Execution
('ben-horowitz', 'Ben Horowitz', 'Wartime CEO Coach', 'leadership', ARRAY['Wartime/peacetime CEO','The hard thing about hard things','Management debt','Culture'], ARRAY['leadership','management','culture','hard decisions'], '#2d5a3d', 'free', 16, 'Co-founder of a16z. Wrote the definitive guide to the ugly, emotional reality of running a startup.'),
('jocko-willink', 'Jocko Willink', 'Extreme Ownership Leader', 'leadership', ARRAY['Extreme ownership','Discipline equals freedom','Dichotomy of leadership','Default aggressive'], ARRAY['leadership','discipline','teams','execution'], '#2d5a3d', 'pro', 17, 'Former Navy SEAL commander. Teaches that every problem is a leadership problem — and leaders must own all of it.'),
('jim-collins', 'Jim Collins', 'Greatness Researcher', 'leadership', ARRAY['Good to Great','Hedgehog concept','Flywheel','Level 5 leadership','BHAG'], ARRAY['org design','greatness','focus','research'], '#2d5a3d', 'pro', 18, 'Spent decades researching why some companies make the leap to greatness while others don''t. Data over opinions.'),
('andy-grove', 'Andy Grove', 'High Output Manager', 'leadership', ARRAY['OKRs','Only the paranoid survive','Strategic inflection points','High output management'], ARRAY['management','operations','pivots','execution'], '#2d5a3d', 'pro', 19, 'Former Intel CEO. Pioneered OKRs and taught managers to recognize when everything about a business must change.'),
-- Sales & Revenue
('marc-benioff', 'Marc Benioff', 'SaaS Sales Pioneer', 'sales', ARRAY['V2MOM','Land-and-expand','SaaS playbook','Ohana culture'], ARRAY['enterprise sales','SaaS','GTM','culture'], '#b8860b', 'pro', 20, 'Founder of Salesforce. Invented the SaaS business model and proved enterprise software could be sold through the cloud.'),
('chris-voss', 'Chris Voss', 'Master Negotiator', 'sales', ARRAY['Tactical empathy','Mirroring','Labeling','Calibrated questions'], ARRAY['negotiation','deals','psychology','influence'], '#b8860b', 'free', 21, 'Former FBI lead hostage negotiator. Applies crisis negotiation techniques to business deals and everyday persuasion.'),
('aaron-ross', 'Aaron Ross', 'Outbound Revenue Expert', 'sales', ARRAY['Predictable revenue','SDR model','Cold calling 2.0','Outbound playbook'], ARRAY['outbound','pipeline','B2B sales','SDR'], '#b8860b', 'pro', 22, 'Built Salesforce''s outbound engine from $0 to $100M. Wrote the bible on creating predictable B2B revenue pipelines.'),
-- Investing & Finance
('nassim-taleb', 'Nassim Taleb', 'Antifragility Thinker', 'investing', ARRAY['Antifragile','Black swans','Skin in the game','Barbell strategy'], ARRAY['risk','uncertainty','optionality','philosophy'], '#4a6a82', 'pro', 23, 'Former options trader turned philosopher. Argues the world rewards those who benefit from disorder rather than predict it.'),
('naval-ravikant', 'Naval Ravikant', 'Wealth & Wisdom Oracle', 'investing', ARRAY['Leverage','Specific knowledge','Wealth creation','Judgment over labor'], ARRAY['leverage','wealth','philosophy','startups'], '#4a6a82', 'free', 24, 'Co-founder of AngelList. Distilled wealth creation into first principles: leverage, specific knowledge, and judgment.'),
-- Behavioral Science
('daniel-kahneman', 'Daniel Kahneman', 'Decision Science Pioneer', 'behavioral', ARRAY['System 1/System 2','Cognitive biases','Prospect theory','Pre-mortem'], ARRAY['decisions','psychology','biases','risk'], '#4a2d6b', 'free', 25, 'Nobel laureate psychologist. Proved that human decision-making is systematically irrational — and showed how to correct for it.'),
('robert-cialdini', 'Robert Cialdini', 'Persuasion Scientist', 'behavioral', ARRAY['Reciprocity','Commitment & consistency','Social proof','Authority','Liking','Scarcity'], ARRAY['influence','persuasion','marketing','psychology'], '#4a2d6b', 'pro', 26, 'Godfather of influence. Identified the six universal principles of persuasion that drive human decision-making.'),
-- Creative & Unconventional
('elon-musk', 'Elon Musk', 'First Principles Engineer', 'creative', ARRAY['First principles reasoning','10x ambition','Rapid iteration','Physics-based thinking'], ARRAY['moonshots','engineering','speed','ambition'], '#e85d3a', 'free', 27, 'CEO of Tesla and SpaceX. Breaks impossible problems down to physics-level first principles and rebuilds from there.'),
('richard-feynman', 'Richard Feynman', 'Curious Problem-Solver', 'creative', ARRAY['First principles physics','Intellectual honesty','What I cannot create I do not understand','Simplify to explain'], ARRAY['problem-solving','science','clarity','curiosity'], '#e85d3a', 'pro', 28, 'Nobel physicist and legendary teacher. Believed if you can''t explain something simply, you don''t understand it well enough.'),
('sam-walton', 'Sam Walton', 'Retail Operations Genius', 'creative', ARRAY['Everyday low price','Store-level obsession','Servant leadership','Frugality'], ARRAY['retail','operations','frugality','customers'], '#e85d3a', 'pro', 29, 'Founded Walmart. Built the world''s largest retailer by obsessing over operations and passing savings to customers.'),
('oprah-winfrey', 'Oprah Winfrey', 'Audience Connection Master', 'creative', ARRAY['Authenticity','Audience connection','Storytelling','Live your best life'], ARRAY['media','brand','audience','storytelling'], '#e85d3a', 'free', 30, 'Media mogul and cultural icon. Built a billion-dollar brand through authentic connection and empowering her audience.')
ON CONFLICT (slug) DO NOTHING;
